version: "3.0"
services:
  nginx-server:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ../../frontend:/static_files
