version: "3.0"
services:
  elasticsearch-server:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    container_name: elasticsearch-server
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
# networks:
#   net:
