FROM jenkins/jenkins:latest
MAINTAINER minho <minhob38@gmail.com>
LABEL purpose=jenkins-server
USER root
COPY ./install-docker.sh /install-docker.sh
WORKDIR /
RUN chmod 777 /install-docker.sh
RUN /install-docker.sh
RUN usermod -aG docker jenkins
USER jenkins
EXPOSE 8080

# chomod로 host의 /var/run/docker.sock permission 수정