version: "3.0"
services:
  elasticsearch-server:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana-server:
    build:
      context: .
      dockerfile: Dockerfile.kibana
    container_name: kibana-server
    # depends_on:
    #   - elasticsearch-server
    # environment:
    # - ELASTICSEARCH_=http://localhost:9200
    # ELASTICSEARCH_HOSTS: '["http://elasticsearchasdsadsadserver:9200"]'
    # volumes:
    #   - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - elk
networks:
  elk:
    driver: bridge
