version: "3.0"
services:
  jenkins-server:
    image: jenkins/jenkins:latest
    container_name: jenkins-server
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins-volume:/var/jenkins-volume
    networks:
      - net
networks:
  net:
