version: "3.0"
services:
  jenkins-server:
    # build:
    # image: jenkins/jenkins:latest
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-server
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
networks:
  net:
